//! This code was AUTOGENERATED using the Codama library.
use {
    crate::types::{FeeTier, Fees},
    solana_pubkey::Pubkey,
};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct UpdateStableFeeConfigEventEvent {
    pub timestamp: i64,
    pub admin: Pubkey,
    pub fee_config: Pubkey,
    pub stable_fee_tiers: Vec<FeeTier>,
    pub flat_fees: Fees,
}

impl UpdateStableFeeConfigEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [94, 5, 43, 237, 103, 147, 232, 245] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
