//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts},
    solana_pubkey::Pubkey,
};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentInitialize {
    pub authority: Pubkey,
    pub buyback_bps: u16,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AgentInitializeInstructionAccounts {
    pub authority: solana_pubkey::Pubkey,
    pub bonding_curve: solana_pubkey::Pubkey,
    pub global_config: solana_pubkey::Pubkey,
    pub mint: solana_pubkey::Pubkey,
    pub token_agent_payments: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub sharing_fee_config: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl AgentInitialize {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [180, 248, 163, 8, 49, 94, 126, 96] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for AgentInitialize {
    type ArrangedAccounts = AgentInitializeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let authority = next_account(&mut iter)?;
        let bonding_curve = next_account(&mut iter)?;
        let global_config = next_account(&mut iter)?;
        let mint = next_account(&mut iter)?;
        let token_agent_payments = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;
        let sharing_fee_config = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(AgentInitializeInstructionAccounts {
            authority,
            bonding_curve,
            global_config,
            mint,
            token_agent_payments,
            system_program,
            event_authority,
            program,
            sharing_fee_config,
            remaining: remaining.to_vec(),
        })
    }
}
