//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentAcceptPayment {
    pub amount: u64,
    pub memo: u64,
    pub start_time: i64,
    pub end_time: i64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AgentAcceptPaymentInstructionAccounts {
    pub user: solana_pubkey::Pubkey,
    pub user_token_account: solana_pubkey::Pubkey,
    pub token_agent_payments: solana_pubkey::Pubkey,
    pub token_agent_associated_account: solana_pubkey::Pubkey,
    pub token_agent_payment_in_currency: solana_pubkey::Pubkey,
    pub global_config: solana_pubkey::Pubkey,
    pub invoice_id: solana_pubkey::Pubkey,
    pub currency_mint: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl AgentAcceptPayment {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [34, 157, 64, 220, 74, 32, 48, 225] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for AgentAcceptPayment {
    type ArrangedAccounts = AgentAcceptPaymentInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let user = next_account(&mut iter)?;
        let user_token_account = next_account(&mut iter)?;
        let token_agent_payments = next_account(&mut iter)?;
        let token_agent_associated_account = next_account(&mut iter)?;
        let token_agent_payment_in_currency = next_account(&mut iter)?;
        let global_config = next_account(&mut iter)?;
        let invoice_id = next_account(&mut iter)?;
        let currency_mint = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(AgentAcceptPaymentInstructionAccounts {
            user,
            user_token_account,
            token_agent_payments,
            token_agent_associated_account,
            token_agent_payment_in_currency,
            global_config,
            invoice_id,
            currency_mint,
            token_program,
            associated_token_program,
            system_program,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
