//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentTransferExtraLamports {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AgentTransferExtraLamportsInstructionAccounts {
    pub token_agent_payments: solana_pubkey::Pubkey,
    pub token_agent_associated_account: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl AgentTransferExtraLamports {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [39, 206, 214, 167, 55, 44, 221, 81] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for AgentTransferExtraLamports {
    type ArrangedAccounts = AgentTransferExtraLamportsInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let token_agent_payments = next_account(&mut iter)?;
        let token_agent_associated_account = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(AgentTransferExtraLamportsInstructionAccounts {
            token_agent_payments,
            token_agent_associated_account,
            remaining: remaining.to_vec(),
        })
    }
}
