//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{account_utils::next_account, deserialize::ArrangeAccounts};
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentBuybackTrigger {
    pub swap_instruction_data: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AgentBuybackTriggerInstructionAccounts {
    pub global_buyback_authority: solana_pubkey::Pubkey,
    pub mint: solana_pubkey::Pubkey,
    pub token_agent_payments: solana_pubkey::Pubkey,
    pub token_agent_payment_in_currency: solana_pubkey::Pubkey,
    pub currency_mint: solana_pubkey::Pubkey,
    pub global_config: solana_pubkey::Pubkey,
    pub swap_program_to_invoke: solana_pubkey::Pubkey,
    pub burn_authority: solana_pubkey::Pubkey,
    pub burn_mint_vault: solana_pubkey::Pubkey,
    pub burn_currency_mint_vault: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub token_program_currency: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl AgentBuybackTrigger {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [95, 231, 193, 2, 245, 75, 125, 155] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}

impl ArrangeAccounts for AgentBuybackTrigger {
    type ArrangedAccounts = AgentBuybackTriggerInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let global_buyback_authority = next_account(&mut iter)?;
        let mint = next_account(&mut iter)?;
        let token_agent_payments = next_account(&mut iter)?;
        let token_agent_payment_in_currency = next_account(&mut iter)?;
        let currency_mint = next_account(&mut iter)?;
        let global_config = next_account(&mut iter)?;
        let swap_program_to_invoke = next_account(&mut iter)?;
        let burn_authority = next_account(&mut iter)?;
        let burn_mint_vault = next_account(&mut iter)?;
        let burn_currency_mint_vault = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let token_program_currency = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(AgentBuybackTriggerInstructionAccounts {
            global_buyback_authority,
            mint,
            token_agent_payments,
            token_agent_payment_in_currency,
            currency_mint,
            global_config,
            swap_program_to_invoke,
            burn_authority,
            burn_mint_vault,
            burn_currency_mint_vault,
            token_program,
            token_program_currency,
            associated_token_program,
            system_program,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
