//! This code was AUTOGENERATED using the Codama library.

pub use super::super::events;
use carbon_core::{borsh, deserialize::ArrangeAccounts};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(
    Debug,
    Clone,
    carbon_core::borsh::BorshSerialize,
    carbon_core::borsh::BorshDeserialize,
    PartialEq,
)]
pub enum CpiEvent {
    AgentAcceptPaymentEvent(events::agent_accept_payment_event::AgentAcceptPaymentEventEvent),
    AgentBuybackTriggerEvent(events::agent_buyback_trigger_event::AgentBuybackTriggerEventEvent),
    AgentDistributePaymentsEvent(
        events::agent_distribute_payments_event::AgentDistributePaymentsEventEvent,
    ),
    AgentInitializeEvent(events::agent_initialize_event::AgentInitializeEventEvent),
    AgentUpdateAuthorityEvent(events::agent_update_authority_event::AgentUpdateAuthorityEventEvent),
    AgentUpdateBuybackBpsEvent(
        events::agent_update_buyback_bps_event::AgentUpdateBuybackBpsEventEvent,
    ),
    AgentWithdrawEvent(events::agent_withdraw_event::AgentWithdrawEventEvent),
    ExtendAccountEvent(events::extend_account_event::ExtendAccountEventEvent),
    GlobalAddNewCurrencyEvent(
        events::global_add_new_currency_event::GlobalAddNewCurrencyEventEvent,
    ),
    GlobalConfigInitializeEvent(
        events::global_config_initialize_event::GlobalConfigInitializeEventEvent,
    ),
    GlobalUpdateAuthoritiesEvent(
        events::global_update_authorities_event::GlobalUpdateAuthoritiesEventEvent,
    ),
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CpiEventInstructionAccounts {
    pub program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CpiEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [228, 69, 165, 46, 81, 203, 154, 29] {
            return None;
        }

        let event_data = &data[8..];

        if let Some(decoded) =
            events::agent_accept_payment_event::AgentAcceptPaymentEventEvent::decode(event_data)
        {
            return Some(CpiEvent::AgentAcceptPaymentEvent(decoded));
        }
        if let Some(decoded) =
            events::agent_buyback_trigger_event::AgentBuybackTriggerEventEvent::decode(event_data)
        {
            return Some(CpiEvent::AgentBuybackTriggerEvent(decoded));
        }
        if let Some(decoded) =
            events::agent_distribute_payments_event::AgentDistributePaymentsEventEvent::decode(
                event_data,
            )
        {
            return Some(CpiEvent::AgentDistributePaymentsEvent(decoded));
        }
        if let Some(decoded) =
            events::agent_initialize_event::AgentInitializeEventEvent::decode(event_data)
        {
            return Some(CpiEvent::AgentInitializeEvent(decoded));
        }
        if let Some(decoded) =
            events::agent_update_authority_event::AgentUpdateAuthorityEventEvent::decode(event_data)
        {
            return Some(CpiEvent::AgentUpdateAuthorityEvent(decoded));
        }
        if let Some(decoded) =
            events::agent_update_buyback_bps_event::AgentUpdateBuybackBpsEventEvent::decode(
                event_data,
            )
        {
            return Some(CpiEvent::AgentUpdateBuybackBpsEvent(decoded));
        }
        if let Some(decoded) =
            events::agent_withdraw_event::AgentWithdrawEventEvent::decode(event_data)
        {
            return Some(CpiEvent::AgentWithdrawEvent(decoded));
        }
        if let Some(decoded) =
            events::extend_account_event::ExtendAccountEventEvent::decode(event_data)
        {
            return Some(CpiEvent::ExtendAccountEvent(decoded));
        }
        if let Some(decoded) =
            events::global_add_new_currency_event::GlobalAddNewCurrencyEventEvent::decode(
                event_data,
            )
        {
            return Some(CpiEvent::GlobalAddNewCurrencyEvent(decoded));
        }
        if let Some(decoded) =
            events::global_config_initialize_event::GlobalConfigInitializeEventEvent::decode(
                event_data,
            )
        {
            return Some(CpiEvent::GlobalConfigInitializeEvent(decoded));
        }
        if let Some(decoded) =
            events::global_update_authorities_event::GlobalUpdateAuthoritiesEventEvent::decode(
                event_data,
            )
        {
            return Some(CpiEvent::GlobalUpdateAuthoritiesEvent(decoded));
        }
        None
    }
}

impl ArrangeAccounts for CpiEvent {
    type ArrangedAccounts = CpiEventInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let [program, event_authority, remaining @ ..] = accounts else {
            return None;
        };

        Some(CpiEventInstructionAccounts {
            program: program.pubkey,
            event_authority: event_authority.pubkey,
            remaining: remaining.to_vec(),
        })
    }
}
