//! This code was AUTOGENERATED using the Codama library.
use crate::{PumpAgentPaymentsDecoder, PROGRAM_ID};

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod agent_accept_payment;
pub mod agent_buyback_trigger;
pub mod agent_distribute_payments;
pub mod agent_initialize;
pub mod agent_transfer_extra_lamports;
pub mod agent_update_authority;
pub mod agent_update_buyback_bps;
pub mod agent_withdraw;
pub mod close_account;
pub mod cpi_event;
pub mod extend_account;
pub mod global_add_new_currency;
pub mod global_config_initialize;
pub mod global_remove_currency;
pub mod global_update_authorities;

pub use self::{
    agent_accept_payment::*, agent_buyback_trigger::*, agent_distribute_payments::*,
    agent_initialize::*, agent_transfer_extra_lamports::*, agent_update_authority::*,
    agent_update_buyback_bps::*, agent_withdraw::*, close_account::*, cpi_event::*,
    extend_account::*, global_add_new_currency::*, global_config_initialize::*,
    global_remove_currency::*, global_update_authorities::*,
};

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PumpAgentPaymentsInstruction {
    AgentAcceptPayment(AgentAcceptPayment),
    AgentBuybackTrigger(AgentBuybackTrigger),
    AgentDistributePayments(AgentDistributePayments),
    AgentInitialize(AgentInitialize),
    AgentTransferExtraLamports(AgentTransferExtraLamports),
    AgentUpdateAuthority(AgentUpdateAuthority),
    AgentUpdateBuybackBps(AgentUpdateBuybackBps),
    AgentWithdraw(AgentWithdraw),
    CloseAccount(CloseAccount),
    ExtendAccount(ExtendAccount),
    GlobalAddNewCurrency(GlobalAddNewCurrency),
    GlobalConfigInitialize(GlobalConfigInitialize),
    GlobalRemoveCurrency(GlobalRemoveCurrency),
    GlobalUpdateAuthorities(GlobalUpdateAuthorities),
    // Anchor CPI Event Instruction
    CpiEvent(Box<CpiEvent>),
}

impl carbon_core::instruction::InstructionDecoder<'_> for PumpAgentPaymentsDecoder {
    type InstructionType = PumpAgentPaymentsInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if instruction.program_id != PROGRAM_ID {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = agent_accept_payment::AgentAcceptPayment::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::AgentAcceptPayment(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = agent_buyback_trigger::AgentBuybackTrigger::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::AgentBuybackTrigger(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = agent_distribute_payments::AgentDistributePayments::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::AgentDistributePayments(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = agent_initialize::AgentInitialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::AgentInitialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                agent_transfer_extra_lamports::AgentTransferExtraLamports::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::AgentTransferExtraLamports(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = agent_update_authority::AgentUpdateAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::AgentUpdateAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = agent_update_buyback_bps::AgentUpdateBuybackBps::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::AgentUpdateBuybackBps(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = agent_withdraw::AgentWithdraw::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::AgentWithdraw(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = close_account::CloseAccount::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::CloseAccount(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = extend_account::ExtendAccount::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::ExtendAccount(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = global_add_new_currency::GlobalAddNewCurrency::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::GlobalAddNewCurrency(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = global_config_initialize::GlobalConfigInitialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::GlobalConfigInitialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = global_remove_currency::GlobalRemoveCurrency::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::GlobalRemoveCurrency(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = global_update_authorities::GlobalUpdateAuthorities::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::GlobalUpdateAuthorities(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAgentPaymentsInstruction::CpiEvent(Box::new(decoded)),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
