//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I128, I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "BoostBuyAndBurnEvent")]
pub struct BoostBuyAndBurnEventGraphQL {
    pub timestamp: I64,
    pub mint: Pubkey,
    pub bonding_curve: Pubkey,
    pub pool: Pubkey,
    pub authority: Pubkey,
    pub quote_amount_in_requested: U64,
    pub quote_amount_in_used: U64,
    pub base_amount_burned: U64,
    pub virtual_quote_reserves: I128,
    pub real_quote_reserves_after: U64,
    pub base_reserves_after: U64,
    pub boost_vault_remaining: U64,
}

impl From<crate::types::BoostBuyAndBurnEvent> for BoostBuyAndBurnEventGraphQL {
    fn from(original: crate::types::BoostBuyAndBurnEvent) -> Self {
        Self {
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
            mint: carbon_core::graphql::primitives::Pubkey(original.mint),
            bonding_curve: carbon_core::graphql::primitives::Pubkey(original.bonding_curve),
            pool: carbon_core::graphql::primitives::Pubkey(original.pool),
            authority: carbon_core::graphql::primitives::Pubkey(original.authority),
            quote_amount_in_requested: carbon_core::graphql::primitives::U64(
                original.quote_amount_in_requested,
            ),
            quote_amount_in_used: carbon_core::graphql::primitives::U64(
                original.quote_amount_in_used,
            ),
            base_amount_burned: carbon_core::graphql::primitives::U64(original.base_amount_burned),
            virtual_quote_reserves: carbon_core::graphql::primitives::I128(
                original.virtual_quote_reserves,
            ),
            real_quote_reserves_after: carbon_core::graphql::primitives::U64(
                original.real_quote_reserves_after,
            ),
            base_reserves_after: carbon_core::graphql::primitives::U64(
                original.base_reserves_after,
            ),
            boost_vault_remaining: carbon_core::graphql::primitives::U64(
                original.boost_vault_remaining,
            ),
        }
    }
}
