//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I128, I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitBoostEvent")]
pub struct InitBoostEventGraphQL {
    pub timestamp: I64,
    pub mint: Pubkey,
    pub bonding_curve: Pubkey,
    pub pool: Pubkey,
    pub virtual_quote_reserves: I128,
    pub real_quote_reserves_after: U64,
}

impl From<crate::types::InitBoostEvent> for InitBoostEventGraphQL {
    fn from(original: crate::types::InitBoostEvent) -> Self {
        Self {
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
            mint: carbon_core::graphql::primitives::Pubkey(original.mint),
            bonding_curve: carbon_core::graphql::primitives::Pubkey(original.bonding_curve),
            pool: carbon_core::graphql::primitives::Pubkey(original.pool),
            virtual_quote_reserves: carbon_core::graphql::primitives::I128(
                original.virtual_quote_reserves,
            ),
            real_quote_reserves_after: carbon_core::graphql::primitives::U64(
                original.real_quote_reserves_after,
            ),
        }
    }
}
