//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitBoostEvent")]
pub struct InitBoostEventGraphQL {
    pub timestamp: I64,
    pub pool: Pubkey,
    pub sigma: U64,
    pub real_quote_reserves_after: U64,
}

impl From<crate::types::InitBoostEvent> for InitBoostEventGraphQL {
    fn from(original: crate::types::InitBoostEvent) -> Self {
        Self {
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
            pool: carbon_core::graphql::primitives::Pubkey(original.pool),
            sigma: carbon_core::graphql::primitives::U64(original.sigma),
            real_quote_reserves_after: carbon_core::graphql::primitives::U64(
                original.real_quote_reserves_after,
            ),
        }
    }
}
