//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "SetBoostAuthorityEvent")]
pub struct SetBoostAuthorityEventGraphQL {
    pub timestamp: I64,
    pub admin: Pubkey,
    pub old_boost_authority: Pubkey,
    pub new_boost_authority: Pubkey,
}

impl From<crate::types::SetBoostAuthorityEvent> for SetBoostAuthorityEventGraphQL {
    fn from(original: crate::types::SetBoostAuthorityEvent) -> Self {
        Self {
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
            admin: carbon_core::graphql::primitives::Pubkey(original.admin),
            old_boost_authority: carbon_core::graphql::primitives::Pubkey(
                original.old_boost_authority,
            ),
            new_boost_authority: carbon_core::graphql::primitives::Pubkey(
                original.new_boost_authority,
            ),
        }
    }
}
