//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentInitializeEvent {
    pub token_agent_payments: Pubkey,
    pub mint: Pubkey,
    pub authority: Pubkey,
    pub buyback_bps: u16,
    pub timestamp: i64,
    pub tokenized_agent_sequence: u64,
}
