//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentDistributePaymentsEvent {
    pub token_agent_payments: Pubkey,
    pub currency_mint: Pubkey,
    pub buyback_bps: u16,
    pub buyback_amount: u64,
    pub withdraw_amount: u64,
    pub timestamp: i64,
}
