//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentWithdrawEvent {
    pub tokenized_agent_mint: Pubkey,
    pub currency_mint: Pubkey,
    pub amount: u64,
    pub receiver: Pubkey,
    pub timestamp: i64,
}
