//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentAcceptPaymentEvent {
    pub user: Pubkey,
    pub tokenized_agent_mint: Pubkey,
    pub token_agent_payments: Pubkey,
    pub currency_mint: Pubkey,
    pub amount: u64,
    pub memo: u64,
    pub start_time: i64,
    pub end_time: i64,
    pub invoice_id: Pubkey,
    pub agent_post_balance: u64,
    pub timestamp: i64,
}
