//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct GlobalAddNewCurrencyEvent {
    pub global_config: Pubkey,
    pub currency_mint: Pubkey,
    pub timestamp: i64,
}
