//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct GlobalUpdateAuthoritiesEvent {
    pub global_config: Pubkey,
    pub protocol_authority: Option<Pubkey>,
    pub buyback_authority: Option<Pubkey>,
    pub timestamp: i64,
}
