//! This code was AUTOGENERATED using the Codama library.
#[cfg(feature = "graphql")]
pub mod graphql;

pub mod agent_accept_payment_event;
pub mod agent_buyback_trigger_event;
pub mod agent_distribute_payments_event;
pub mod agent_initialize_event;
pub mod agent_update_authority_event;
pub mod agent_update_buyback_bps_event;
pub mod agent_withdraw_event;
pub mod extend_account_event;
pub mod global_add_new_currency_event;
pub mod global_config_initialize_event;
pub mod global_update_authorities_event;

pub use self::{
    agent_accept_payment_event::*, agent_buyback_trigger_event::*,
    agent_distribute_payments_event::*, agent_initialize_event::*, agent_update_authority_event::*,
    agent_update_buyback_bps_event::*, agent_withdraw_event::*, extend_account_event::*,
    global_add_new_currency_event::*, global_config_initialize_event::*,
    global_update_authorities_event::*,
};
