//! This code was AUTOGENERATED using the Codama library.
pub mod admin_set_coin_creator_row;
pub mod admin_update_token_incentives_row;
pub mod buy_exact_quote_in_row;
pub mod buy_row;
pub mod claim_cashback_row;
pub mod claim_token_incentives_row;
pub mod close_user_volume_accumulator_row;
pub mod collect_coin_creator_fee_row;
pub mod cpi_event_row;
pub mod create_config_row;
pub mod create_pool_row;
pub mod deposit_row;
pub mod disable_row;
pub mod extend_account_row;
pub mod init_user_volume_accumulator_row;
pub mod migrate_pool_coin_creator_row;
pub mod sell_row;
pub mod set_coin_creator_row;
pub mod set_reserved_fee_recipients_row;
pub mod sync_user_volume_accumulator_row;
pub mod toggle_cashback_enabled_row;
pub mod toggle_mayhem_mode_row;
pub mod transfer_creator_fees_to_pump_row;
pub mod transfer_creator_fees_to_pump_v2_row;
pub mod update_admin_row;
pub mod update_buyback_config_row;
pub mod update_fee_config_row;
pub mod withdraw_row;

pub use self::{
    admin_set_coin_creator_row::*, admin_update_token_incentives_row::*, buy_exact_quote_in_row::*,
    buy_row::*, claim_cashback_row::*, claim_token_incentives_row::*,
    close_user_volume_accumulator_row::*, collect_coin_creator_fee_row::*, cpi_event_row::*,
    create_config_row::*, create_pool_row::*, deposit_row::*, disable_row::*,
    extend_account_row::*, init_user_volume_accumulator_row::*, migrate_pool_coin_creator_row::*,
    sell_row::*, set_coin_creator_row::*, set_reserved_fee_recipients_row::*,
    sync_user_volume_accumulator_row::*, toggle_cashback_enabled_row::*, toggle_mayhem_mode_row::*,
    transfer_creator_fees_to_pump_row::*, transfer_creator_fees_to_pump_v2_row::*,
    update_admin_row::*, update_buyback_config_row::*, update_fee_config_row::*, withdraw_row::*,
};
use super::PumpAmmInstruction;

pub struct PumpAmmInstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for PumpAmmInstructionsMigration {
    fn app(&self) -> &str {
        "pump-amm"
    }

    fn name(&self) -> &str {
        "pump_amm_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(AdminSetCoinCreatorMigrationOperation),
            Box::new(AdminUpdateTokenIncentivesMigrationOperation),
            Box::new(BuyMigrationOperation),
            Box::new(BuyExactQuoteInMigrationOperation),
            Box::new(ClaimCashbackMigrationOperation),
            Box::new(ClaimTokenIncentivesMigrationOperation),
            Box::new(CloseUserVolumeAccumulatorMigrationOperation),
            Box::new(CollectCoinCreatorFeeMigrationOperation),
            Box::new(CreateConfigMigrationOperation),
            Box::new(CreatePoolMigrationOperation),
            Box::new(DepositMigrationOperation),
            Box::new(DisableMigrationOperation),
            Box::new(ExtendAccountMigrationOperation),
            Box::new(InitUserVolumeAccumulatorMigrationOperation),
            Box::new(MigratePoolCoinCreatorMigrationOperation),
            Box::new(SellMigrationOperation),
            Box::new(SetCoinCreatorMigrationOperation),
            Box::new(SetReservedFeeRecipientsMigrationOperation),
            Box::new(SyncUserVolumeAccumulatorMigrationOperation),
            Box::new(ToggleCashbackEnabledMigrationOperation),
            Box::new(ToggleMayhemModeMigrationOperation),
            Box::new(TransferCreatorFeesToPumpMigrationOperation),
            Box::new(TransferCreatorFeesToPumpV2MigrationOperation),
            Box::new(UpdateAdminMigrationOperation),
            Box::new(UpdateBuybackConfigMigrationOperation),
            Box::new(UpdateFeeConfigMigrationOperation),
            Box::new(WithdrawMigrationOperation),
            Box::new(CpiEventMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct PumpAmmInstructionWithMetadata(
    pub PumpAmmInstruction,
    pub carbon_core::instruction::InstructionMetadata,
    pub Vec<solana_instruction::AccountMeta>,
);

impl
    From<(
        PumpAmmInstruction,
        carbon_core::instruction::InstructionMetadata,
        Vec<solana_instruction::AccountMeta>,
    )> for PumpAmmInstructionWithMetadata
{
    fn from(
        value: (
            PumpAmmInstruction,
            carbon_core::instruction::InstructionMetadata,
            Vec<solana_instruction::AccountMeta>,
        ),
    ) -> Self {
        PumpAmmInstructionWithMetadata(value.0, value.1, value.2)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for PumpAmmInstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let PumpAmmInstructionWithMetadata(instruction, metadata, accounts) = self;
        match instruction {
            PumpAmmInstruction::AdminSetCoinCreator(instruction) => {
                let row = admin_set_coin_creator_row::AdminSetCoinCreatorRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::AdminUpdateTokenIncentives(instruction) => {
                let row =
                    admin_update_token_incentives_row::AdminUpdateTokenIncentivesRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Buy(instruction) => {
                let row = buy_row::BuyRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::BuyExactQuoteIn(instruction) => {
                let row = buy_exact_quote_in_row::BuyExactQuoteInRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ClaimCashback(instruction) => {
                let row = claim_cashback_row::ClaimCashbackRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ClaimTokenIncentives(instruction) => {
                let row = claim_token_incentives_row::ClaimTokenIncentivesRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CloseUserVolumeAccumulator(instruction) => {
                let row =
                    close_user_volume_accumulator_row::CloseUserVolumeAccumulatorRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CollectCoinCreatorFee(instruction) => {
                let row = collect_coin_creator_fee_row::CollectCoinCreatorFeeRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CreateConfig(instruction) => {
                let row = create_config_row::CreateConfigRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CreatePool(instruction) => {
                let row = create_pool_row::CreatePoolRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Deposit(instruction) => {
                let row = deposit_row::DepositRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Disable(instruction) => {
                let row = disable_row::DisableRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ExtendAccount(instruction) => {
                let row = extend_account_row::ExtendAccountRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::InitUserVolumeAccumulator(instruction) => {
                let row =
                    init_user_volume_accumulator_row::InitUserVolumeAccumulatorRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::MigratePoolCoinCreator(instruction) => {
                let row = migrate_pool_coin_creator_row::MigratePoolCoinCreatorRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Sell(instruction) => {
                let row = sell_row::SellRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::SetCoinCreator(instruction) => {
                let row = set_coin_creator_row::SetCoinCreatorRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::SetReservedFeeRecipients(instruction) => {
                let row = set_reserved_fee_recipients_row::SetReservedFeeRecipientsRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::SyncUserVolumeAccumulator(instruction) => {
                let row =
                    sync_user_volume_accumulator_row::SyncUserVolumeAccumulatorRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ToggleCashbackEnabled(instruction) => {
                let row = toggle_cashback_enabled_row::ToggleCashbackEnabledRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ToggleMayhemMode(instruction) => {
                let row = toggle_mayhem_mode_row::ToggleMayhemModeRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::TransferCreatorFeesToPump(instruction) => {
                let row =
                    transfer_creator_fees_to_pump_row::TransferCreatorFeesToPumpRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::TransferCreatorFeesToPumpV2(instruction) => {
                let row = transfer_creator_fees_to_pump_v2_row::TransferCreatorFeesToPumpV2Row::from_parts(instruction.clone(), metadata.clone(), accounts.clone());
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::UpdateAdmin(instruction) => {
                let row = update_admin_row::UpdateAdminRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::UpdateBuybackConfig(instruction) => {
                let row = update_buyback_config_row::UpdateBuybackConfigRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::UpdateFeeConfig(instruction) => {
                let row = update_fee_config_row::UpdateFeeConfigRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Withdraw(instruction) => {
                let row = withdraw_row::WithdrawRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(
                    (**instruction).clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for PumpAmmInstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let PumpAmmInstructionWithMetadata(instruction, metadata, accounts) = self;
        match instruction {
            PumpAmmInstruction::AdminSetCoinCreator(instruction) => {
                let row = admin_set_coin_creator_row::AdminSetCoinCreatorRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::AdminUpdateTokenIncentives(instruction) => {
                let row =
                    admin_update_token_incentives_row::AdminUpdateTokenIncentivesRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Buy(instruction) => {
                let row = buy_row::BuyRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::BuyExactQuoteIn(instruction) => {
                let row = buy_exact_quote_in_row::BuyExactQuoteInRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ClaimCashback(instruction) => {
                let row = claim_cashback_row::ClaimCashbackRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ClaimTokenIncentives(instruction) => {
                let row = claim_token_incentives_row::ClaimTokenIncentivesRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CloseUserVolumeAccumulator(instruction) => {
                let row =
                    close_user_volume_accumulator_row::CloseUserVolumeAccumulatorRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CollectCoinCreatorFee(instruction) => {
                let row = collect_coin_creator_fee_row::CollectCoinCreatorFeeRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CreateConfig(instruction) => {
                let row = create_config_row::CreateConfigRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CreatePool(instruction) => {
                let row = create_pool_row::CreatePoolRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Deposit(instruction) => {
                let row = deposit_row::DepositRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Disable(instruction) => {
                let row = disable_row::DisableRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ExtendAccount(instruction) => {
                let row = extend_account_row::ExtendAccountRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::InitUserVolumeAccumulator(instruction) => {
                let row =
                    init_user_volume_accumulator_row::InitUserVolumeAccumulatorRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::MigratePoolCoinCreator(instruction) => {
                let row = migrate_pool_coin_creator_row::MigratePoolCoinCreatorRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Sell(instruction) => {
                let row = sell_row::SellRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::SetCoinCreator(instruction) => {
                let row = set_coin_creator_row::SetCoinCreatorRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::SetReservedFeeRecipients(instruction) => {
                let row = set_reserved_fee_recipients_row::SetReservedFeeRecipientsRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::SyncUserVolumeAccumulator(instruction) => {
                let row =
                    sync_user_volume_accumulator_row::SyncUserVolumeAccumulatorRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ToggleCashbackEnabled(instruction) => {
                let row = toggle_cashback_enabled_row::ToggleCashbackEnabledRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::ToggleMayhemMode(instruction) => {
                let row = toggle_mayhem_mode_row::ToggleMayhemModeRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::TransferCreatorFeesToPump(instruction) => {
                let row =
                    transfer_creator_fees_to_pump_row::TransferCreatorFeesToPumpRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::TransferCreatorFeesToPumpV2(instruction) => {
                let row = transfer_creator_fees_to_pump_v2_row::TransferCreatorFeesToPumpV2Row::from_parts(instruction.clone(), metadata.clone(), accounts.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::UpdateAdmin(instruction) => {
                let row = update_admin_row::UpdateAdminRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::UpdateBuybackConfig(instruction) => {
                let row = update_buyback_config_row::UpdateBuybackConfigRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::UpdateFeeConfig(instruction) => {
                let row = update_fee_config_row::UpdateFeeConfigRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::Withdraw(instruction) => {
                let row = withdraw_row::WithdrawRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAmmInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(
                    (**instruction).clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
