//! This code was AUTOGENERATED using the Codama library.
use crate::{PumpFeesDecoder, PROGRAM_ID};

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod claim_social_fee_pda;
pub mod claim_social_fee_pda_v2;
pub mod cpi_event;
pub mod crank_donation_fee_pda;
pub mod create_donation_fee_pda;
pub mod create_fee_sharing_config;
pub mod create_social_fee_pda;
pub mod extend_fee_config;
pub mod get_fees;
pub mod initialize_buyback;
pub mod initialize_fee_config;
pub mod initialize_fee_program_global;
pub mod reset_fee_sharing_config;
pub mod reset_fee_sharing_config_v2;
pub mod revoke_fee_sharing_authority;
pub mod set_authority;
pub mod set_claim_rate_limit;
pub mod set_disable_flags;
pub mod set_social_claim_authority;
pub mod sweep_buyback;
pub mod transfer_fee_sharing_authority;
pub mod update_admin;
pub mod update_buyback_authority;
pub mod update_buyback_claim_rate_limit;
pub mod update_fee_config;
pub mod update_fee_shares;
pub mod update_fee_shares_v2;
pub mod update_stable_fee_config;
pub mod upsert_fee_tiers;
pub mod upsert_stable_fee_tiers;

pub use self::{
    claim_social_fee_pda::*, claim_social_fee_pda_v2::*, cpi_event::*, crank_donation_fee_pda::*,
    create_donation_fee_pda::*, create_fee_sharing_config::*, create_social_fee_pda::*,
    extend_fee_config::*, get_fees::*, initialize_buyback::*, initialize_fee_config::*,
    initialize_fee_program_global::*, reset_fee_sharing_config::*, reset_fee_sharing_config_v2::*,
    revoke_fee_sharing_authority::*, set_authority::*, set_claim_rate_limit::*,
    set_disable_flags::*, set_social_claim_authority::*, sweep_buyback::*,
    transfer_fee_sharing_authority::*, update_admin::*, update_buyback_authority::*,
    update_buyback_claim_rate_limit::*, update_fee_config::*, update_fee_shares::*,
    update_fee_shares_v2::*, update_stable_fee_config::*, upsert_fee_tiers::*,
    upsert_stable_fee_tiers::*,
};

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PumpFeesInstruction {
    ClaimSocialFeePda(ClaimSocialFeePda),
    ClaimSocialFeePdaV2(ClaimSocialFeePdaV2),
    CrankDonationFeePda(CrankDonationFeePda),
    CreateDonationFeePda(CreateDonationFeePda),
    CreateFeeSharingConfig(CreateFeeSharingConfig),
    CreateSocialFeePda(CreateSocialFeePda),
    ExtendFeeConfig(ExtendFeeConfig),
    GetFees(GetFees),
    InitializeBuyback(InitializeBuyback),
    InitializeFeeConfig(InitializeFeeConfig),
    InitializeFeeProgramGlobal(InitializeFeeProgramGlobal),
    ResetFeeSharingConfig(ResetFeeSharingConfig),
    ResetFeeSharingConfigV2(ResetFeeSharingConfigV2),
    RevokeFeeSharingAuthority(RevokeFeeSharingAuthority),
    SetAuthority(SetAuthority),
    SetClaimRateLimit(SetClaimRateLimit),
    SetDisableFlags(SetDisableFlags),
    SetSocialClaimAuthority(SetSocialClaimAuthority),
    SweepBuyback(SweepBuyback),
    TransferFeeSharingAuthority(TransferFeeSharingAuthority),
    UpdateAdmin(UpdateAdmin),
    UpdateBuybackAuthority(UpdateBuybackAuthority),
    UpdateBuybackClaimRateLimit(UpdateBuybackClaimRateLimit),
    UpdateFeeConfig(UpdateFeeConfig),
    UpdateFeeShares(UpdateFeeShares),
    UpdateFeeSharesV2(UpdateFeeSharesV2),
    UpdateStableFeeConfig(UpdateStableFeeConfig),
    UpsertFeeTiers(UpsertFeeTiers),
    UpsertStableFeeTiers(UpsertStableFeeTiers),
    // Anchor CPI Event Instruction
    CpiEvent(Box<CpiEvent>),
}

impl carbon_core::instruction::InstructionDecoder<'_> for PumpFeesDecoder {
    type InstructionType = PumpFeesInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if instruction.program_id != PROGRAM_ID {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = claim_social_fee_pda::ClaimSocialFeePda::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::ClaimSocialFeePda(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_social_fee_pda_v2::ClaimSocialFeePdaV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::ClaimSocialFeePdaV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = crank_donation_fee_pda::CrankDonationFeePda::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::CrankDonationFeePda(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_donation_fee_pda::CreateDonationFeePda::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::CreateDonationFeePda(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_fee_sharing_config::CreateFeeSharingConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::CreateFeeSharingConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_social_fee_pda::CreateSocialFeePda::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::CreateSocialFeePda(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = extend_fee_config::ExtendFeeConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::ExtendFeeConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = get_fees::GetFees::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::GetFees(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize_buyback::InitializeBuyback::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::InitializeBuyback(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize_fee_config::InitializeFeeConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::InitializeFeeConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                initialize_fee_program_global::InitializeFeeProgramGlobal::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::InitializeFeeProgramGlobal(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = reset_fee_sharing_config::ResetFeeSharingConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::ResetFeeSharingConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                reset_fee_sharing_config_v2::ResetFeeSharingConfigV2::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::ResetFeeSharingConfigV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                revoke_fee_sharing_authority::RevokeFeeSharingAuthority::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::RevokeFeeSharingAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_authority::SetAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::SetAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_claim_rate_limit::SetClaimRateLimit::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::SetClaimRateLimit(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_disable_flags::SetDisableFlags::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::SetDisableFlags(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_social_claim_authority::SetSocialClaimAuthority::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::SetSocialClaimAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = sweep_buyback::SweepBuyback::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::SweepBuyback(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                transfer_fee_sharing_authority::TransferFeeSharingAuthority::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::TransferFeeSharingAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_admin::UpdateAdmin::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpdateAdmin(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_buyback_authority::UpdateBuybackAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpdateBuybackAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                update_buyback_claim_rate_limit::UpdateBuybackClaimRateLimit::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpdateBuybackClaimRateLimit(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_fee_config::UpdateFeeConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpdateFeeConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_fee_shares::UpdateFeeShares::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpdateFeeShares(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_fee_shares_v2::UpdateFeeSharesV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpdateFeeSharesV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_stable_fee_config::UpdateStableFeeConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpdateStableFeeConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = upsert_fee_tiers::UpsertFeeTiers::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpsertFeeTiers(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = upsert_stable_fee_tiers::UpsertStableFeeTiers::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::UpsertStableFeeTiers(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpFeesInstruction::CpiEvent(Box::new(decoded)),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
