//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentAcceptPaymentEvent")]
pub struct AgentAcceptPaymentEventGraphQL {
    pub user: Pubkey,
    pub tokenized_agent_mint: Pubkey,
    pub token_agent_payments: Pubkey,
    pub currency_mint: Pubkey,
    pub amount: U64,
    pub memo: U64,
    pub start_time: I64,
    pub end_time: I64,
    pub invoice_id: Pubkey,
    pub agent_post_balance: U64,
    pub timestamp: I64,
}

impl From<crate::types::AgentAcceptPaymentEvent> for AgentAcceptPaymentEventGraphQL {
    fn from(original: crate::types::AgentAcceptPaymentEvent) -> Self {
        Self {
            user: carbon_core::graphql::primitives::Pubkey(original.user),
            tokenized_agent_mint: carbon_core::graphql::primitives::Pubkey(
                original.tokenized_agent_mint,
            ),
            token_agent_payments: carbon_core::graphql::primitives::Pubkey(
                original.token_agent_payments,
            ),
            currency_mint: carbon_core::graphql::primitives::Pubkey(original.currency_mint),
            amount: carbon_core::graphql::primitives::U64(original.amount),
            memo: carbon_core::graphql::primitives::U64(original.memo),
            start_time: carbon_core::graphql::primitives::I64(original.start_time),
            end_time: carbon_core::graphql::primitives::I64(original.end_time),
            invoice_id: carbon_core::graphql::primitives::Pubkey(original.invoice_id),
            agent_post_balance: carbon_core::graphql::primitives::U64(original.agent_post_balance),
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
        }
    }
}
