//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentUpdateBuybackBpsEvent")]
pub struct AgentUpdateBuybackBpsEventGraphQL {
    pub token_agent_payments: Pubkey,
    pub mint: Pubkey,
    pub old_buyback_bps: i32,
    pub new_buyback_bps: i32,
    pub timestamp: I64,
}

impl From<crate::types::AgentUpdateBuybackBpsEvent> for AgentUpdateBuybackBpsEventGraphQL {
    fn from(original: crate::types::AgentUpdateBuybackBpsEvent) -> Self {
        Self {
            token_agent_payments: carbon_core::graphql::primitives::Pubkey(
                original.token_agent_payments,
            ),
            mint: carbon_core::graphql::primitives::Pubkey(original.mint),
            old_buyback_bps: original.old_buyback_bps as i32,
            new_buyback_bps: original.new_buyback_bps as i32,
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
        }
    }
}
