//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentDistributePaymentsEvent")]
pub struct AgentDistributePaymentsEventGraphQL {
    pub token_agent_payments: Pubkey,
    pub currency_mint: Pubkey,
    pub buyback_bps: i32,
    pub buyback_amount: U64,
    pub withdraw_amount: U64,
    pub timestamp: I64,
}

impl From<crate::types::AgentDistributePaymentsEvent> for AgentDistributePaymentsEventGraphQL {
    fn from(original: crate::types::AgentDistributePaymentsEvent) -> Self {
        Self {
            token_agent_payments: carbon_core::graphql::primitives::Pubkey(
                original.token_agent_payments,
            ),
            currency_mint: carbon_core::graphql::primitives::Pubkey(original.currency_mint),
            buyback_bps: original.buyback_bps as i32,
            buyback_amount: carbon_core::graphql::primitives::U64(original.buyback_amount),
            withdraw_amount: carbon_core::graphql::primitives::U64(original.withdraw_amount),
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
        }
    }
}
