//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentWithdrawEvent")]
pub struct AgentWithdrawEventGraphQL {
    pub tokenized_agent_mint: Pubkey,
    pub currency_mint: Pubkey,
    pub amount: U64,
    pub receiver: Pubkey,
    pub timestamp: I64,
}

impl From<crate::types::AgentWithdrawEvent> for AgentWithdrawEventGraphQL {
    fn from(original: crate::types::AgentWithdrawEvent) -> Self {
        Self {
            tokenized_agent_mint: carbon_core::graphql::primitives::Pubkey(
                original.tokenized_agent_mint,
            ),
            currency_mint: carbon_core::graphql::primitives::Pubkey(original.currency_mint),
            amount: carbon_core::graphql::primitives::U64(original.amount),
            receiver: carbon_core::graphql::primitives::Pubkey(original.receiver),
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
        }
    }
}
