//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentUpdateAuthorityEvent")]
pub struct AgentUpdateAuthorityEventGraphQL {
    pub token_agent_payments: Pubkey,
    pub old_authority: Pubkey,
    pub new_authority: Pubkey,
    pub timestamp: I64,
}

impl From<crate::types::AgentUpdateAuthorityEvent> for AgentUpdateAuthorityEventGraphQL {
    fn from(original: crate::types::AgentUpdateAuthorityEvent) -> Self {
        Self {
            token_agent_payments: carbon_core::graphql::primitives::Pubkey(
                original.token_agent_payments,
            ),
            old_authority: carbon_core::graphql::primitives::Pubkey(original.old_authority),
            new_authority: carbon_core::graphql::primitives::Pubkey(original.new_authority),
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
        }
    }
}
