//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentInitializeEvent")]
pub struct AgentInitializeEventGraphQL {
    pub token_agent_payments: Pubkey,
    pub mint: Pubkey,
    pub authority: Pubkey,
    pub buyback_bps: i32,
    pub timestamp: I64,
    pub tokenized_agent_sequence: U64,
}

impl From<crate::types::AgentInitializeEvent> for AgentInitializeEventGraphQL {
    fn from(original: crate::types::AgentInitializeEvent) -> Self {
        Self {
            token_agent_payments: carbon_core::graphql::primitives::Pubkey(
                original.token_agent_payments,
            ),
            mint: carbon_core::graphql::primitives::Pubkey(original.mint),
            authority: carbon_core::graphql::primitives::Pubkey(original.authority),
            buyback_bps: original.buyback_bps as i32,
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
            tokenized_agent_sequence: carbon_core::graphql::primitives::U64(
                original.tokenized_agent_sequence,
            ),
        }
    }
}
