//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentBuybackTriggerEvent")]
pub struct AgentBuybackTriggerEventGraphQL {
    pub tokenized_agent_mint: Pubkey,
    pub currency_mint: Pubkey,
    pub amount_burned: U64,
    pub swap_program: Pubkey,
    pub new_tokens_bought_and_burned_for_currency: U64,
    pub agent_post_balance: U64,
    pub timestamp: I64,
    pub currency_mint_amount_for_buyback: U64,
}

impl From<crate::types::AgentBuybackTriggerEvent> for AgentBuybackTriggerEventGraphQL {
    fn from(original: crate::types::AgentBuybackTriggerEvent) -> Self {
        Self {
            tokenized_agent_mint: carbon_core::graphql::primitives::Pubkey(
                original.tokenized_agent_mint,
            ),
            currency_mint: carbon_core::graphql::primitives::Pubkey(original.currency_mint),
            amount_burned: carbon_core::graphql::primitives::U64(original.amount_burned),
            swap_program: carbon_core::graphql::primitives::Pubkey(original.swap_program),
            new_tokens_bought_and_burned_for_currency: carbon_core::graphql::primitives::U64(
                original.new_tokens_bought_and_burned_for_currency,
            ),
            agent_post_balance: carbon_core::graphql::primitives::U64(original.agent_post_balance),
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
            currency_mint_amount_for_buyback: carbon_core::graphql::primitives::U64(
                original.currency_mint_amount_for_buyback,
            ),
        }
    }
}
