//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "GlobalConfigInitializeEvent")]
pub struct GlobalConfigInitializeEventGraphQL {
    pub global_config: Pubkey,
    pub protocol_authority: Pubkey,
    pub buyback_authority: Pubkey,
    pub timestamp: I64,
}

impl From<crate::types::GlobalConfigInitializeEvent> for GlobalConfigInitializeEventGraphQL {
    fn from(original: crate::types::GlobalConfigInitializeEvent) -> Self {
        Self {
            global_config: carbon_core::graphql::primitives::Pubkey(original.global_config),
            protocol_authority: carbon_core::graphql::primitives::Pubkey(
                original.protocol_authority,
            ),
            buyback_authority: carbon_core::graphql::primitives::Pubkey(original.buyback_authority),
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
        }
    }
}
