//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "GlobalUpdateAuthoritiesEvent")]
pub struct GlobalUpdateAuthoritiesEventGraphQL {
    pub global_config: Pubkey,
    pub protocol_authority: Option<Pubkey>,
    pub buyback_authority: Option<Pubkey>,
    pub timestamp: I64,
}

impl From<crate::types::GlobalUpdateAuthoritiesEvent> for GlobalUpdateAuthoritiesEventGraphQL {
    fn from(original: crate::types::GlobalUpdateAuthoritiesEvent) -> Self {
        Self {
            global_config: carbon_core::graphql::primitives::Pubkey(original.global_config),
            protocol_authority: original.protocol_authority.map(Pubkey),
            buyback_authority: original.buyback_authority.map(Pubkey),
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
        }
    }
}
