//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, I64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "GlobalAddNewCurrencyEvent")]
pub struct GlobalAddNewCurrencyEventGraphQL {
    pub global_config: Pubkey,
    pub currency_mint: Pubkey,
    pub timestamp: I64,
}

impl From<crate::types::GlobalAddNewCurrencyEvent> for GlobalAddNewCurrencyEventGraphQL {
    fn from(original: crate::types::GlobalAddNewCurrencyEvent) -> Self {
        Self {
            global_config: carbon_core::graphql::primitives::Pubkey(original.global_config),
            currency_mint: carbon_core::graphql::primitives::Pubkey(original.currency_mint),
            timestamp: carbon_core::graphql::primitives::I64(original.timestamp),
        }
    }
}
