//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct BoostBuyAndBurnEvent {
    pub timestamp: i64,
    pub pool: Pubkey,
    pub authority: Pubkey,
    pub quote_amount_in_requested: u64,
    pub quote_amount_in_used: u64,
    pub base_amount_burned: u64,
    pub virtual_quote_reserves: i128,
    pub real_quote_reserves_after: u64,
    pub base_reserves_after: u64,
    pub boost_vault_remaining: u64,
}
