//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct InitBoostEvent {
    pub timestamp: i64,
    pub pool: Pubkey,
    pub sigma: u64,
    pub real_quote_reserves_after: u64,
}
