//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account::AccountMetadata,
    postgres::{
        metadata::AccountRowMetadata,
        primitives::{Pubkey, U64, U8},
    },
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct GlobalConfigRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub bump: U8,
    pub protocol_authority: Pubkey,
    pub buyback_authority: Pubkey,
    pub supported_currencies_mint: Vec<Pubkey>,
    pub tokenized_agent_sequence: U64,
}

impl GlobalConfigRow {
    pub fn from_parts(
        source: crate::accounts::global_config::GlobalConfig,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            bump: source.bump.into(),
            protocol_authority: source.protocol_authority.into(),
            buyback_authority: source.buyback_authority.into(),
            supported_currencies_mint: source
                .supported_currencies_mint
                .into_iter()
                .map(|element| element.into())
                .collect(),
            tokenized_agent_sequence: source.tokenized_agent_sequence.into(),
        }
    }
}

impl TryFrom<GlobalConfigRow> for crate::accounts::global_config::GlobalConfig {
    type Error = carbon_core::error::Error;
    fn try_from(source: GlobalConfigRow) -> Result<Self, Self::Error> {
        Ok(Self {
            bump: source.bump.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            protocol_authority: *source.protocol_authority,
            buyback_authority: *source.buyback_authority,
            supported_currencies_mint: source
                .supported_currencies_mint
                .into_iter()
                .map(|element| Ok(*element))
                .collect::<Result<Vec<_>, carbon_core::error::Error>>()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to collect array elements".to_string(),
                    )
                })?
                .try_into()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to convert array element to primitive".to_string(),
                    )
                })?,
            tokenized_agent_sequence: *source.tokenized_agent_sequence,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::global_config::GlobalConfig {
    fn table() -> &'static str {
        "global_config_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "bump",
            "protocol_authority",
            "buyback_authority",
            "supported_currencies_mint",
            "tokenized_agent_sequence",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for GlobalConfigRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO global_config_account (
                "bump",
                "protocol_authority",
                "buyback_authority",
                "supported_currencies_mint",
                "tokenized_agent_sequence",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#,
        )
        .bind(self.bump)
        .bind(self.protocol_authority)
        .bind(self.buyback_authority)
        .bind(&self.supported_currencies_mint)
        .bind(&self.tokenized_agent_sequence)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for GlobalConfigRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO global_config_account (
                "bump",
                "protocol_authority",
                "buyback_authority",
                "supported_currencies_mint",
                "tokenized_agent_sequence",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "bump" = EXCLUDED."bump",
                "protocol_authority" = EXCLUDED."protocol_authority",
                "buyback_authority" = EXCLUDED."buyback_authority",
                "supported_currencies_mint" = EXCLUDED."supported_currencies_mint",
                "tokenized_agent_sequence" = EXCLUDED."tokenized_agent_sequence",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.bump)
        .bind(self.protocol_authority)
        .bind(self.buyback_authority)
        .bind(&self.supported_currencies_mint)
        .bind(&self.tokenized_agent_sequence)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for GlobalConfigRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM global_config_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for GlobalConfigRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM global_config_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct GlobalConfigMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for GlobalConfigMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS global_config_account (
                -- Account data
                "bump" INT2 NOT NULL,
                "protocol_authority" BYTEA NOT NULL,
                "buyback_authority" BYTEA NOT NULL,
                "supported_currencies_mint" BYTEA[] NOT NULL,
                "tokenized_agent_sequence" NUMERIC(20) NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS global_config_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
