//! This code was AUTOGENERATED using the Codama library.
pub mod bonding_curve_row;
pub mod global_config_row;
pub mod token_agent_payment_in_currency_row;
pub mod token_agent_payments_row;

pub use self::{
    bonding_curve_row::*, global_config_row::*, token_agent_payment_in_currency_row::*,
    token_agent_payments_row::*,
};
use super::PumpAgentPaymentsAccount;

pub struct PumpAgentPaymentsAccountsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for PumpAgentPaymentsAccountsMigration {
    fn app(&self) -> &str {
        "pump-agent-payments"
    }

    fn name(&self) -> &str {
        "pump_agent_payments_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(BondingCurveMigrationOperation),
            Box::new(GlobalConfigMigrationOperation),
            Box::new(TokenAgentPaymentInCurrencyMigrationOperation),
            Box::new(TokenAgentPaymentsMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct PumpAgentPaymentsAccountWithMetadata(
    pub PumpAgentPaymentsAccount,
    pub carbon_core::account::AccountMetadata,
);

impl
    From<(
        PumpAgentPaymentsAccount,
        carbon_core::account::AccountMetadata,
    )> for PumpAgentPaymentsAccountWithMetadata
{
    fn from(
        value: (
            PumpAgentPaymentsAccount,
            carbon_core::account::AccountMetadata,
        ),
    ) -> Self {
        PumpAgentPaymentsAccountWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for PumpAgentPaymentsAccountWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let PumpAgentPaymentsAccountWithMetadata(account, metadata) = self;

        match account {
            PumpAgentPaymentsAccount::BondingCurve(account) => {
                let row = bonding_curve_row::BondingCurveRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsAccount::GlobalConfig(account) => {
                let row = global_config_row::GlobalConfigRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsAccount::TokenAgentPaymentInCurrency(account) => {
                let row =
                    token_agent_payment_in_currency_row::TokenAgentPaymentInCurrencyRow::from_parts(
                        *account.clone(),
                        metadata.clone(),
                    );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsAccount::TokenAgentPayments(account) => {
                let row = token_agent_payments_row::TokenAgentPaymentsRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for PumpAgentPaymentsAccountWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let PumpAgentPaymentsAccountWithMetadata(account, metadata) = self;
        match account {
            PumpAgentPaymentsAccount::BondingCurve(account) => {
                let row = bonding_curve_row::BondingCurveRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsAccount::GlobalConfig(account) => {
                let row = global_config_row::GlobalConfigRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsAccount::TokenAgentPaymentInCurrency(account) => {
                let row =
                    token_agent_payment_in_currency_row::TokenAgentPaymentInCurrencyRow::from_parts(
                        *account.clone(),
                        metadata.clone(),
                    );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsAccount::TokenAgentPayments(account) => {
                let row = token_agent_payments_row::TokenAgentPaymentsRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
