//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account::AccountMetadata,
    postgres::{
        metadata::AccountRowMetadata,
        primitives::{Pubkey, U16, U8},
    },
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct TokenAgentPaymentsRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub bump: U8,
    pub mint: Pubkey,
    pub authority: Pubkey,
    pub buyback_bps: U16,
}

impl TokenAgentPaymentsRow {
    pub fn from_parts(
        source: crate::accounts::token_agent_payments::TokenAgentPayments,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            bump: source.bump.into(),
            mint: source.mint.into(),
            authority: source.authority.into(),
            buyback_bps: source.buyback_bps.into(),
        }
    }
}

impl TryFrom<TokenAgentPaymentsRow> for crate::accounts::token_agent_payments::TokenAgentPayments {
    type Error = carbon_core::error::Error;
    fn try_from(source: TokenAgentPaymentsRow) -> Result<Self, Self::Error> {
        Ok(Self {
            bump: source.bump.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            mint: *source.mint,
            authority: *source.authority,
            buyback_bps: source.buyback_bps.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::accounts::token_agent_payments::TokenAgentPayments
{
    fn table() -> &'static str {
        "token_agent_payments_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "bump",
            "mint",
            "authority",
            "buyback_bps",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for TokenAgentPaymentsRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO token_agent_payments_account (
                "bump",
                "mint",
                "authority",
                "buyback_bps",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            )"#,
        )
        .bind(self.bump)
        .bind(self.mint)
        .bind(self.authority)
        .bind(self.buyback_bps)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for TokenAgentPaymentsRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO token_agent_payments_account (
                "bump",
                "mint",
                "authority",
                "buyback_bps",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "bump" = EXCLUDED."bump",
                "mint" = EXCLUDED."mint",
                "authority" = EXCLUDED."authority",
                "buyback_bps" = EXCLUDED."buyback_bps",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.bump)
        .bind(self.mint)
        .bind(self.authority)
        .bind(self.buyback_bps)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for TokenAgentPaymentsRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM token_agent_payments_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for TokenAgentPaymentsRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM token_agent_payments_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct TokenAgentPaymentsMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for TokenAgentPaymentsMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS token_agent_payments_account (
                -- Account data
                "bump" INT2 NOT NULL,
                "mint" BYTEA NOT NULL,
                "authority" BYTEA NOT NULL,
                "buyback_bps" INT4 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS token_agent_payments_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
