//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    account::AccountMetadata,
    postgres::{
        metadata::AccountRowMetadata,
        primitives::{Pubkey, U64},
    },
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct TokenAgentPaymentInCurrencyRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub mint: Pubkey,
    pub currency_mint: Pubkey,
    pub total_invoice_payments_made: U64,
    pub total_buyback: U64,
    pub total_withdrawals: U64,
    pub tokens_bought_back_and_burned: U64,
}

impl TokenAgentPaymentInCurrencyRow {
    pub fn from_parts(
        source: crate::accounts::token_agent_payment_in_currency::TokenAgentPaymentInCurrency,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            mint: source.mint.into(),
            currency_mint: source.currency_mint.into(),
            total_invoice_payments_made: source.total_invoice_payments_made.into(),
            total_buyback: source.total_buyback.into(),
            total_withdrawals: source.total_withdrawals.into(),
            tokens_bought_back_and_burned: source.tokens_bought_back_and_burned.into(),
        }
    }
}

impl TryFrom<TokenAgentPaymentInCurrencyRow>
    for crate::accounts::token_agent_payment_in_currency::TokenAgentPaymentInCurrency
{
    type Error = carbon_core::error::Error;
    fn try_from(source: TokenAgentPaymentInCurrencyRow) -> Result<Self, Self::Error> {
        Ok(Self {
            mint: *source.mint,
            currency_mint: *source.currency_mint,
            total_invoice_payments_made: *source.total_invoice_payments_made,
            total_buyback: *source.total_buyback,
            total_withdrawals: *source.total_withdrawals,
            tokens_bought_back_and_burned: *source.tokens_bought_back_and_burned,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::accounts::token_agent_payment_in_currency::TokenAgentPaymentInCurrency
{
    fn table() -> &'static str {
        "token_agent_payment_in_currency_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "mint",
            "currency_mint",
            "total_invoice_payments_made",
            "total_buyback",
            "total_withdrawals",
            "tokens_bought_back_and_burned",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for TokenAgentPaymentInCurrencyRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO token_agent_payment_in_currency_account (
                "mint",
                "currency_mint",
                "total_invoice_payments_made",
                "total_buyback",
                "total_withdrawals",
                "tokens_bought_back_and_burned",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            )"#,
        )
        .bind(self.mint)
        .bind(self.currency_mint)
        .bind(&self.total_invoice_payments_made)
        .bind(&self.total_buyback)
        .bind(&self.total_withdrawals)
        .bind(&self.tokens_bought_back_and_burned)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for TokenAgentPaymentInCurrencyRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO token_agent_payment_in_currency_account (
                "mint",
                "currency_mint",
                "total_invoice_payments_made",
                "total_buyback",
                "total_withdrawals",
                "tokens_bought_back_and_burned",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "mint" = EXCLUDED."mint",
                "currency_mint" = EXCLUDED."currency_mint",
                "total_invoice_payments_made" = EXCLUDED."total_invoice_payments_made",
                "total_buyback" = EXCLUDED."total_buyback",
                "total_withdrawals" = EXCLUDED."total_withdrawals",
                "tokens_bought_back_and_burned" = EXCLUDED."tokens_bought_back_and_burned",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.mint)
        .bind(self.currency_mint)
        .bind(&self.total_invoice_payments_made)
        .bind(&self.total_buyback)
        .bind(&self.total_withdrawals)
        .bind(&self.tokens_bought_back_and_burned)
        .bind(self.account_metadata.pubkey)
        .bind(&self.account_metadata.slot)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for TokenAgentPaymentInCurrencyRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM token_agent_payment_in_currency_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for TokenAgentPaymentInCurrencyRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM token_agent_payment_in_currency_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct TokenAgentPaymentInCurrencyMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for TokenAgentPaymentInCurrencyMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS token_agent_payment_in_currency_account (
                -- Account data
                "mint" BYTEA NOT NULL,
                "currency_mint" BYTEA NOT NULL,
                "total_invoice_payments_made" NUMERIC(20) NOT NULL,
                "total_buyback" NUMERIC(20) NOT NULL,
                "total_withdrawals" NUMERIC(20) NOT NULL,
                "tokens_bought_back_and_burned" NUMERIC(20) NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS token_agent_payment_in_currency_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
