//! This code was AUTOGENERATED using the Codama library.
use crate::{PumpAmmDecoder, PROGRAM_ID};

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod admin_set_coin_creator;
pub mod admin_update_token_incentives;
pub mod boost_buy_and_burn;
pub mod buy;
pub mod buy_exact_quote_in;
pub mod claim_cashback;
pub mod claim_token_incentives;
pub mod close_user_volume_accumulator;
pub mod collect_coin_creator_fee;
pub mod cpi_event;
pub mod create_config;
pub mod create_pool;
pub mod deposit;
pub mod disable;
pub mod extend_account;
pub mod init_boost;
pub mod init_user_volume_accumulator;
pub mod migrate_pool_coin_creator;
pub mod sell;
pub mod set_boost_authority;
pub mod set_coin_creator;
pub mod set_reserved_fee_recipients;
pub mod sync_user_volume_accumulator;
pub mod toggle_boost;
pub mod toggle_cashback_enabled;
pub mod toggle_mayhem_mode;
pub mod transfer_creator_fees_to_pump;
pub mod transfer_creator_fees_to_pump_v2;
pub mod update_admin;
pub mod update_buyback_config;
pub mod update_fee_config;
pub mod withdraw;

pub use self::{
    admin_set_coin_creator::*, admin_update_token_incentives::*, boost_buy_and_burn::*, buy::*,
    buy_exact_quote_in::*, claim_cashback::*, claim_token_incentives::*,
    close_user_volume_accumulator::*, collect_coin_creator_fee::*, cpi_event::*, create_config::*,
    create_pool::*, deposit::*, disable::*, extend_account::*, init_boost::*,
    init_user_volume_accumulator::*, migrate_pool_coin_creator::*, sell::*, set_boost_authority::*,
    set_coin_creator::*, set_reserved_fee_recipients::*, sync_user_volume_accumulator::*,
    toggle_boost::*, toggle_cashback_enabled::*, toggle_mayhem_mode::*,
    transfer_creator_fees_to_pump::*, transfer_creator_fees_to_pump_v2::*, update_admin::*,
    update_buyback_config::*, update_fee_config::*, withdraw::*,
};

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PumpAmmInstruction {
    AdminSetCoinCreator(AdminSetCoinCreator),
    AdminUpdateTokenIncentives(AdminUpdateTokenIncentives),
    BoostBuyAndBurn(BoostBuyAndBurn),
    Buy(Buy),
    BuyExactQuoteIn(BuyExactQuoteIn),
    ClaimCashback(ClaimCashback),
    ClaimTokenIncentives(ClaimTokenIncentives),
    CloseUserVolumeAccumulator(CloseUserVolumeAccumulator),
    CollectCoinCreatorFee(CollectCoinCreatorFee),
    CreateConfig(CreateConfig),
    CreatePool(CreatePool),
    Deposit(Deposit),
    Disable(Disable),
    ExtendAccount(ExtendAccount),
    InitBoost(InitBoost),
    InitUserVolumeAccumulator(InitUserVolumeAccumulator),
    MigratePoolCoinCreator(MigratePoolCoinCreator),
    Sell(Sell),
    SetBoostAuthority(SetBoostAuthority),
    SetCoinCreator(SetCoinCreator),
    SetReservedFeeRecipients(SetReservedFeeRecipients),
    SyncUserVolumeAccumulator(SyncUserVolumeAccumulator),
    ToggleBoost(ToggleBoost),
    ToggleCashbackEnabled(ToggleCashbackEnabled),
    ToggleMayhemMode(ToggleMayhemMode),
    TransferCreatorFeesToPump(TransferCreatorFeesToPump),
    TransferCreatorFeesToPumpV2(TransferCreatorFeesToPumpV2),
    UpdateAdmin(UpdateAdmin),
    UpdateBuybackConfig(UpdateBuybackConfig),
    UpdateFeeConfig(UpdateFeeConfig),
    Withdraw(Withdraw),
    // Anchor CPI Event Instruction
    CpiEvent(Box<CpiEvent>),
}

impl carbon_core::instruction::InstructionDecoder<'_> for PumpAmmDecoder {
    type InstructionType = PumpAmmInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if instruction.program_id != PROGRAM_ID {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = admin_set_coin_creator::AdminSetCoinCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::AdminSetCoinCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                admin_update_token_incentives::AdminUpdateTokenIncentives::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::AdminUpdateTokenIncentives(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = boost_buy_and_burn::BoostBuyAndBurn::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::BoostBuyAndBurn(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = buy::Buy::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::Buy(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = buy_exact_quote_in::BuyExactQuoteIn::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::BuyExactQuoteIn(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_cashback::ClaimCashback::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::ClaimCashback(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_token_incentives::ClaimTokenIncentives::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::ClaimTokenIncentives(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                close_user_volume_accumulator::CloseUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::CloseUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = collect_coin_creator_fee::CollectCoinCreatorFee::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::CollectCoinCreatorFee(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_config::CreateConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::CreateConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_pool::CreatePool::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::CreatePool(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = deposit::Deposit::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::Deposit(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = disable::Disable::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::Disable(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = extend_account::ExtendAccount::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::ExtendAccount(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = init_boost::InitBoost::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::InitBoost(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                init_user_volume_accumulator::InitUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::InitUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = migrate_pool_coin_creator::MigratePoolCoinCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::MigratePoolCoinCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = sell::Sell::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::Sell(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_boost_authority::SetBoostAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::SetBoostAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_coin_creator::SetCoinCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::SetCoinCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                set_reserved_fee_recipients::SetReservedFeeRecipients::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::SetReservedFeeRecipients(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                sync_user_volume_accumulator::SyncUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::SyncUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = toggle_boost::ToggleBoost::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::ToggleBoost(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = toggle_cashback_enabled::ToggleCashbackEnabled::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::ToggleCashbackEnabled(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = toggle_mayhem_mode::ToggleMayhemMode::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::ToggleMayhemMode(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                transfer_creator_fees_to_pump::TransferCreatorFeesToPump::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::TransferCreatorFeesToPump(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                transfer_creator_fees_to_pump_v2::TransferCreatorFeesToPumpV2::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::TransferCreatorFeesToPumpV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_admin::UpdateAdmin::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::UpdateAdmin(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_buyback_config::UpdateBuybackConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::UpdateBuybackConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_fee_config::UpdateFeeConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::UpdateFeeConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = withdraw::Withdraw::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::Withdraw(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpAmmInstruction::CpiEvent(Box::new(decoded)),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
