//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U64, U8},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "GlobalConfig")]
pub struct GlobalConfigGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub bump: U8,
    pub protocol_authority: Pubkey,
    pub buyback_authority: Pubkey,
    pub supported_currencies_mint: Vec<Pubkey>,
    pub tokenized_agent_sequence: U64,
}

impl TryFrom<crate::accounts::postgres::GlobalConfigRow> for GlobalConfigGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::GlobalConfigRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
            protocol_authority: carbon_core::graphql::primitives::Pubkey(row.protocol_authority.0),
            buyback_authority: carbon_core::graphql::primitives::Pubkey(row.buyback_authority.0),
            supported_currencies_mint: row
                .supported_currencies_mint
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::Pubkey(item.0))
                .collect(),
            tokenized_agent_sequence: carbon_core::graphql::primitives::U64(
                *row.tokenized_agent_sequence,
            ),
        })
    }
}
