//! This code was AUTOGENERATED using the Codama library.
pub mod bonding_curve_schema;
pub mod global_config_schema;
pub mod token_agent_payment_in_currency_schema;
pub mod token_agent_payments_schema;

use juniper::GraphQLObject;
pub use {
    bonding_curve_schema::*, global_config_schema::*, token_agent_payment_in_currency_schema::*,
    token_agent_payments_schema::*,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AccountMetadata")]
pub struct AccountMetadataGraphQL {
    pub pubkey: carbon_core::graphql::primitives::Pubkey,
    pub slot: Option<carbon_core::graphql::primitives::U64>,
}

impl From<carbon_core::postgres::metadata::AccountRowMetadata> for AccountMetadataGraphQL {
    fn from(metadata: carbon_core::postgres::metadata::AccountRowMetadata) -> Self {
        Self {
            pubkey: carbon_core::graphql::primitives::Pubkey(*metadata.pubkey),
            slot: metadata
                .slot
                .map(|v| carbon_core::graphql::primitives::U64(*v)),
        }
    }
}
