//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U8},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "TokenAgentPayments")]
pub struct TokenAgentPaymentsGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub bump: U8,
    pub mint: Pubkey,
    pub authority: Pubkey,
    pub buyback_bps: i32,
}

impl TryFrom<crate::accounts::postgres::TokenAgentPaymentsRow> for TokenAgentPaymentsGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::accounts::postgres::TokenAgentPaymentsRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
            mint: carbon_core::graphql::primitives::Pubkey(row.mint.0),
            authority: carbon_core::graphql::primitives::Pubkey(row.authority.0),
            buyback_bps: *row.buyback_bps,
        })
    }
}
