//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{Pubkey, U64},
    juniper::GraphQLObject,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "TokenAgentPaymentInCurrency")]
pub struct TokenAgentPaymentInCurrencyGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub mint: Pubkey,
    pub currency_mint: Pubkey,
    pub total_invoice_payments_made: U64,
    pub total_buyback: U64,
    pub total_withdrawals: U64,
    pub tokens_bought_back_and_burned: U64,
}

impl TryFrom<crate::accounts::postgres::TokenAgentPaymentInCurrencyRow>
    for TokenAgentPaymentInCurrencyGraphQL
{
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::accounts::postgres::TokenAgentPaymentInCurrencyRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            mint: carbon_core::graphql::primitives::Pubkey(row.mint.0),
            currency_mint: carbon_core::graphql::primitives::Pubkey(row.currency_mint.0),
            total_invoice_payments_made: carbon_core::graphql::primitives::U64(
                *row.total_invoice_payments_made,
            ),
            total_buyback: carbon_core::graphql::primitives::U64(*row.total_buyback),
            total_withdrawals: carbon_core::graphql::primitives::U64(*row.total_withdrawals),
            tokens_bought_back_and_burned: carbon_core::graphql::primitives::U64(
                *row.tokens_bought_back_and_burned,
            ),
        })
    }
}
