//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::U64, juniper::GraphQLObject, serde_json};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "BoostBuyAndBurn")]
pub struct BoostBuyAndBurnGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub quote_amount_in: U64,
    pub min_base_amount_burned: U64,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::BoostBuyAndBurnRow> for BoostBuyAndBurnGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::BoostBuyAndBurnRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            quote_amount_in: carbon_core::graphql::primitives::U64(*row.quote_amount_in),
            min_base_amount_burned: carbon_core::graphql::primitives::U64(
                *row.min_base_amount_burned,
            ),
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
