//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentBuybackTriggerEventEvent {
    pub tokenized_agent_mint: Pubkey,
    pub currency_mint: Pubkey,
    pub amount_burned: u64,
    pub swap_program: Pubkey,
    pub new_tokens_bought_and_burned_for_currency: u64,
    pub agent_post_balance: u64,
    pub timestamp: i64,
    pub currency_mint_amount_for_buyback: u64,
}

impl AgentBuybackTriggerEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [139, 240, 9, 225, 214, 63, 232, 165] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
