//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentDistributePaymentsEventEvent {
    pub token_agent_payments: Pubkey,
    pub currency_mint: Pubkey,
    pub buyback_bps: u16,
    pub buyback_amount: u64,
    pub withdraw_amount: u64,
    pub timestamp: i64,
}

impl AgentDistributePaymentsEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [137, 116, 114, 140, 54, 111, 230, 26] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
