//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentAcceptPaymentEventEvent {
    pub user: Pubkey,
    pub tokenized_agent_mint: Pubkey,
    pub token_agent_payments: Pubkey,
    pub currency_mint: Pubkey,
    pub amount: u64,
    pub memo: u64,
    pub start_time: i64,
    pub end_time: i64,
    pub invoice_id: Pubkey,
    pub agent_post_balance: u64,
    pub timestamp: i64,
}

impl AgentAcceptPaymentEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [114, 190, 188, 192, 105, 79, 41, 147] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
