//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AgentInitializeEventEvent {
    pub token_agent_payments: Pubkey,
    pub mint: Pubkey,
    pub authority: Pubkey,
    pub buyback_bps: u16,
    pub timestamp: i64,
    pub tokenized_agent_sequence: u64,
}

impl AgentInitializeEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [192, 5, 183, 151, 0, 64, 100, 207] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
