//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct GlobalUpdateAuthoritiesEventEvent {
    pub global_config: Pubkey,
    pub protocol_authority: Option<Pubkey>,
    pub buyback_authority: Option<Pubkey>,
    pub timestamp: i64,
}

impl GlobalUpdateAuthoritiesEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [82, 27, 22, 232, 53, 66, 35, 207] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
