//! This code was AUTOGENERATED using the Codama library.
use {crate::types::GameMode, solana_pubkey::Pubkey};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct CreateEventEvent {
    pub name: String,
    pub symbol: String,
    pub uri: String,
    pub mint: Pubkey,
    pub bonding_curve: Pubkey,
    pub user: Pubkey,
    pub creator: Pubkey,
    pub timestamp: i64,
    pub virtual_token_reserves: u64,
    pub virtual_sol_reserves: u64,
    pub real_token_reserves: u64,
    pub token_total_supply: u64,
    pub token_program: Pubkey,
    pub is_mayhem_mode: bool,
    pub is_cashback_enabled: bool,
    pub quote_mint: Pubkey,
    pub virtual_quote_reserves: u64,
    /// Trailing field appended by the program after the original layout;
    /// events emitted before the upgrade have no bytes for it. Skipped by
    /// the borsh derive and read manually in `decode` so both layouts parse.
    #[borsh(skip)]
    pub game_mode: Option<GameMode>,
}

impl CreateEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [27, 114, 169, 77, 222, 235, 99, 118] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        let mut event: Self = borsh::BorshDeserialize::deserialize(&mut data_slice).ok()?;
        if !data_slice.is_empty() {
            // Unknown trailing data (e.g. a game-mode variant newer than this
            // decoder) degrades to no game mode rather than dropping the event.
            event.game_mode = borsh::BorshDeserialize::deserialize(&mut data_slice).unwrap_or(None);
        }
        Some(event)
    }
}

#[cfg(test)]
mod tests {
    use {super::*, borsh::BorshSerialize};

    fn event() -> CreateEventEvent {
        CreateEventEvent {
            name: "coin".into(),
            symbol: "COIN".into(),
            uri: "https://example.com/meta.json".into(),
            mint: Pubkey::new_unique(),
            bonding_curve: Pubkey::new_unique(),
            user: Pubkey::new_unique(),
            creator: Pubkey::new_unique(),
            timestamp: 1_700_000_000,
            virtual_token_reserves: 1,
            virtual_sol_reserves: 2,
            real_token_reserves: 3,
            token_total_supply: 4,
            token_program: Pubkey::new_unique(),
            is_mayhem_mode: true,
            is_cashback_enabled: false,
            quote_mint: Pubkey::new_unique(),
            virtual_quote_reserves: 5,
            game_mode: None,
        }
    }

    /// The borsh derive skips `game_mode`, so serializing produces exactly the
    /// pre-upgrade wire layout; trailing bytes are appended per test case.
    fn encode(trailing: &[u8]) -> Vec<u8> {
        let mut data = vec![27, 114, 169, 77, 222, 235, 99, 118];
        event().serialize(&mut data).unwrap();
        data.extend_from_slice(trailing);
        data
    }

    #[test]
    fn decodes_pre_upgrade_layout_without_game_mode() {
        let decoded = CreateEventEvent::decode(&encode(&[])).unwrap();
        assert_eq!(decoded.game_mode, None);
    }

    #[test]
    fn decodes_trailing_game_mode_none() {
        let decoded = CreateEventEvent::decode(&encode(&[0])).unwrap();
        assert_eq!(decoded.game_mode, None);
    }

    #[test]
    fn decodes_trailing_game_mode_some() {
        let decoded = CreateEventEvent::decode(&encode(&[1, 2])).unwrap();
        assert_eq!(decoded.game_mode, Some(GameMode::Climb));
    }

    #[test]
    fn unknown_game_mode_variant_degrades_to_none() {
        let decoded = CreateEventEvent::decode(&encode(&[1, 9])).unwrap();
        assert_eq!(decoded.game_mode, None);
    }
}
