//! This code was AUTOGENERATED using the Codama library.
use crate::{PumpDecoder, PROGRAM_ID};

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod add_quote_mint;
pub mod admin_set_creator;
pub mod admin_set_idl_authority;
pub mod admin_update_token_incentives;
pub mod buy;
pub mod buy_exact_quote_in_v2;
pub mod buy_exact_sol_in;
pub mod buy_v2;
pub mod claim_cashback;
pub mod claim_cashback_v2;
pub mod claim_token_incentives;
pub mod close_user_volume_accumulator;
pub mod collect_creator_fee;
pub mod collect_creator_fee_v2;
pub mod cpi_event;
pub mod create;
pub mod create_v2;
pub mod create_v3;
pub mod distribute_creator_fees;
pub mod distribute_creator_fees_v2;
pub mod extend_account;
pub mod get_minimum_distributable_fee;
pub mod init_user_volume_accumulator;
pub mod initialize;
pub mod migrate;
pub mod migrate_bonding_curve_creator;
pub mod migrate_v2;
pub mod remove_quote_mint;
pub mod sell;
pub mod sell_v2;
pub mod set_creator;
pub mod set_mayhem_virtual_params;
pub mod set_metaplex_creator;
pub mod set_params;
pub mod set_reserved_fee_recipients;
pub mod set_virtual_quote_reserves;
pub mod sync_user_volume_accumulator;
pub mod toggle_cashback_enabled;
pub mod toggle_create_v2;
pub mod toggle_mayhem_mode;
pub mod update_buyback_config;
pub mod update_global_authority;

pub use self::{
    add_quote_mint::*, admin_set_creator::*, admin_set_idl_authority::*,
    admin_update_token_incentives::*, buy::*, buy_exact_quote_in_v2::*, buy_exact_sol_in::*,
    buy_v2::*, claim_cashback::*, claim_cashback_v2::*, claim_token_incentives::*,
    close_user_volume_accumulator::*, collect_creator_fee::*, collect_creator_fee_v2::*,
    cpi_event::*, create::*, create_v2::*, create_v3::*, distribute_creator_fees::*,
    distribute_creator_fees_v2::*, extend_account::*, get_minimum_distributable_fee::*,
    init_user_volume_accumulator::*, initialize::*, migrate::*, migrate_bonding_curve_creator::*,
    migrate_v2::*, remove_quote_mint::*, sell::*, sell_v2::*, set_creator::*,
    set_mayhem_virtual_params::*, set_metaplex_creator::*, set_params::*,
    set_reserved_fee_recipients::*, set_virtual_quote_reserves::*, sync_user_volume_accumulator::*,
    toggle_cashback_enabled::*, toggle_create_v2::*, toggle_mayhem_mode::*,
    update_buyback_config::*, update_global_authority::*,
};

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PumpInstruction {
    AddQuoteMint(AddQuoteMint),
    AdminSetCreator(AdminSetCreator),
    AdminSetIdlAuthority(AdminSetIdlAuthority),
    AdminUpdateTokenIncentives(AdminUpdateTokenIncentives),
    Buy(Buy),
    BuyExactQuoteInV2(BuyExactQuoteInV2),
    BuyExactSolIn(BuyExactSolIn),
    BuyV2(BuyV2),
    ClaimCashback(ClaimCashback),
    ClaimCashbackV2(ClaimCashbackV2),
    ClaimTokenIncentives(ClaimTokenIncentives),
    CloseUserVolumeAccumulator(CloseUserVolumeAccumulator),
    CollectCreatorFee(CollectCreatorFee),
    CollectCreatorFeeV2(CollectCreatorFeeV2),
    Create(Create),
    CreateV2(CreateV2),
    CreateV3(CreateV3),
    DistributeCreatorFees(DistributeCreatorFees),
    DistributeCreatorFeesV2(DistributeCreatorFeesV2),
    ExtendAccount(ExtendAccount),
    GetMinimumDistributableFee(GetMinimumDistributableFee),
    Initialize(Initialize),
    InitUserVolumeAccumulator(InitUserVolumeAccumulator),
    Migrate(Migrate),
    MigrateBondingCurveCreator(MigrateBondingCurveCreator),
    MigrateV2(MigrateV2),
    RemoveQuoteMint(RemoveQuoteMint),
    Sell(Sell),
    SellV2(SellV2),
    SetCreator(SetCreator),
    SetMayhemVirtualParams(SetMayhemVirtualParams),
    SetMetaplexCreator(SetMetaplexCreator),
    SetParams(SetParams),
    SetReservedFeeRecipients(SetReservedFeeRecipients),
    SetVirtualQuoteReserves(SetVirtualQuoteReserves),
    SyncUserVolumeAccumulator(SyncUserVolumeAccumulator),
    ToggleCashbackEnabled(ToggleCashbackEnabled),
    ToggleCreateV2(ToggleCreateV2),
    ToggleMayhemMode(ToggleMayhemMode),
    UpdateBuybackConfig(UpdateBuybackConfig),
    UpdateGlobalAuthority(UpdateGlobalAuthority),
    // Anchor CPI Event Instruction
    CpiEvent(Box<CpiEvent>),
}

impl carbon_core::instruction::InstructionDecoder<'_> for PumpDecoder {
    type InstructionType = PumpInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if instruction.program_id != PROGRAM_ID {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = add_quote_mint::AddQuoteMint::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::AddQuoteMint(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = admin_set_creator::AdminSetCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::AdminSetCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = admin_set_idl_authority::AdminSetIdlAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::AdminSetIdlAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                admin_update_token_incentives::AdminUpdateTokenIncentives::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::AdminUpdateTokenIncentives(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = buy::Buy::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::Buy(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = buy_exact_quote_in_v2::BuyExactQuoteInV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::BuyExactQuoteInV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = buy_exact_sol_in::BuyExactSolIn::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::BuyExactSolIn(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = buy_v2::BuyV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::BuyV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_cashback::ClaimCashback::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::ClaimCashback(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_cashback_v2::ClaimCashbackV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::ClaimCashbackV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_token_incentives::ClaimTokenIncentives::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::ClaimTokenIncentives(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                close_user_volume_accumulator::CloseUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::CloseUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = collect_creator_fee::CollectCreatorFee::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::CollectCreatorFee(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = collect_creator_fee_v2::CollectCreatorFeeV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::CollectCreatorFeeV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create::Create::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::Create(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_v2::CreateV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::CreateV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_v3::CreateV3::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::CreateV3(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = distribute_creator_fees::DistributeCreatorFees::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::DistributeCreatorFees(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = distribute_creator_fees_v2::DistributeCreatorFeesV2::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::DistributeCreatorFeesV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = extend_account::ExtendAccount::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::ExtendAccount(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                get_minimum_distributable_fee::GetMinimumDistributableFee::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::GetMinimumDistributableFee(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                init_user_volume_accumulator::InitUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::InitUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize::Initialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::Initialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = migrate::Migrate::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::Migrate(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                migrate_bonding_curve_creator::MigrateBondingCurveCreator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::MigrateBondingCurveCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = migrate_v2::MigrateV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::MigrateV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = remove_quote_mint::RemoveQuoteMint::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::RemoveQuoteMint(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = sell::Sell::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::Sell(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = sell_v2::SellV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::SellV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_creator::SetCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::SetCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_mayhem_virtual_params::SetMayhemVirtualParams::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::SetMayhemVirtualParams(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_metaplex_creator::SetMetaplexCreator::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::SetMetaplexCreator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_params::SetParams::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::SetParams(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                set_reserved_fee_recipients::SetReservedFeeRecipients::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::SetReservedFeeRecipients(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_virtual_quote_reserves::SetVirtualQuoteReserves::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::SetVirtualQuoteReserves(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                sync_user_volume_accumulator::SyncUserVolumeAccumulator::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::SyncUserVolumeAccumulator(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = toggle_cashback_enabled::ToggleCashbackEnabled::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::ToggleCashbackEnabled(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = toggle_create_v2::ToggleCreateV2::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::ToggleCreateV2(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = toggle_mayhem_mode::ToggleMayhemMode::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::ToggleMayhemMode(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_buyback_config::UpdateBuybackConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::UpdateBuybackConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_global_authority::UpdateGlobalAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::UpdateGlobalAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PumpInstruction::CpiEvent(Box::new(decoded)),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
