//! This code was AUTOGENERATED using the Codama library.
use {
    carbon_core::graphql::primitives::{I64, U64},
    juniper::GraphQLObject,
    serde_json,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentAcceptPayment")]
pub struct AgentAcceptPaymentGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub amount: U64,
    pub memo: U64,
    pub start_time: I64,
    pub end_time: I64,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::AgentAcceptPaymentRow> for AgentAcceptPaymentGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::AgentAcceptPaymentRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            amount: carbon_core::graphql::primitives::U64(*row.amount),
            memo: carbon_core::graphql::primitives::U64(*row.memo),
            start_time: carbon_core::graphql::primitives::I64(row.start_time),
            end_time: carbon_core::graphql::primitives::I64(row.end_time),
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
