//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::U8, juniper::GraphQLObject, serde_json};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentBuybackTrigger")]
pub struct AgentBuybackTriggerGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub swap_instruction_data: Vec<U8>,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::AgentBuybackTriggerRow> for AgentBuybackTriggerGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::AgentBuybackTriggerRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            swap_instruction_data: row
                .swap_instruction_data
                .into_iter()
                .map(carbon_core::graphql::primitives::U8)
                .collect(),
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
