//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::Pubkey, juniper::GraphQLObject, serde_json};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentInitialize")]
pub struct AgentInitializeGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub authority: Pubkey,
    pub buyback_bps: i32,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::AgentInitializeRow> for AgentInitializeGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::AgentInitializeRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            authority: carbon_core::graphql::primitives::Pubkey(row.authority.0),
            buyback_bps: *row.buyback_bps,
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
