//! This code was AUTOGENERATED using the Codama library.
use {carbon_core::graphql::primitives::Pubkey, juniper::GraphQLObject, serde_json};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "GlobalConfigInitialize")]
pub struct GlobalConfigInitializeGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub protocol_authority: Pubkey,
    pub buyback_authority: Pubkey,
    pub accounts: carbon_core::graphql::primitives::Json,
}

impl TryFrom<crate::instructions::postgres::GlobalConfigInitializeRow>
    for GlobalConfigInitializeGraphQL
{
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::GlobalConfigInitializeRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            protocol_authority: carbon_core::graphql::primitives::Pubkey(row.protocol_authority.0),
            buyback_authority: carbon_core::graphql::primitives::Pubkey(row.buyback_authority.0),
            accounts: carbon_core::graphql::primitives::Json(
                serde_json::to_value(&row.accounts.0)
                    .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?,
            ),
        })
    }
}
