//! This code was AUTOGENERATED using the Codama library.
pub mod agent_accept_payment_schema;
pub mod agent_buyback_trigger_schema;
pub mod agent_distribute_payments_schema;
pub mod agent_initialize_schema;
pub mod agent_transfer_extra_lamports_schema;
pub mod agent_update_authority_schema;
pub mod agent_update_buyback_bps_schema;
pub mod agent_withdraw_schema;
pub mod close_account_schema;
pub mod cpi_event_schema;
pub mod extend_account_schema;
pub mod global_add_new_currency_schema;
pub mod global_config_initialize_schema;
pub mod global_remove_currency_schema;
pub mod global_update_authorities_schema;

use juniper::GraphQLObject;
pub use {
    agent_accept_payment_schema::*, agent_buyback_trigger_schema::*,
    agent_distribute_payments_schema::*, agent_initialize_schema::*,
    agent_transfer_extra_lamports_schema::*, agent_update_authority_schema::*,
    agent_update_buyback_bps_schema::*, agent_withdraw_schema::*, close_account_schema::*,
    cpi_event_schema::*, extend_account_schema::*, global_add_new_currency_schema::*,
    global_config_initialize_schema::*, global_remove_currency_schema::*,
    global_update_authorities_schema::*,
};

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InstructionMetadata")]
pub struct InstructionMetadataGraphQL {
    pub signature: String,
    pub instruction_index: carbon_core::graphql::primitives::U32,
    pub stack_height: carbon_core::graphql::primitives::U32,
    pub slot: Option<carbon_core::graphql::primitives::U64>,
}

impl From<carbon_core::postgres::metadata::InstructionRowMetadata> for InstructionMetadataGraphQL {
    fn from(metadata: carbon_core::postgres::metadata::InstructionRowMetadata) -> Self {
        Self {
            signature: metadata.signature,
            instruction_index: carbon_core::graphql::primitives::U32(
                (*metadata.instruction_index) as u32,
            ),
            stack_height: carbon_core::graphql::primitives::U32((*metadata.stack_height) as u32),
            slot: metadata
                .slot
                .map(|v| carbon_core::graphql::primitives::U64(*v)),
        }
    }
}
