//! This code was AUTOGENERATED using the Codama library.
use carbon_core::{
    instruction::InstructionMetadata,
    postgres::{metadata::InstructionRowMetadata, primitives::U64},
};

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct AgentAcceptPaymentRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub amount: U64,
    pub memo: U64,
    pub start_time: i64,
    pub end_time: i64,
    #[sqlx(rename = "__accounts")]
    pub accounts: sqlx::types::Json<Vec<solana_instruction::AccountMeta>>,
}

impl AgentAcceptPaymentRow {
    pub fn from_parts(
        source: crate::instructions::agent_accept_payment::AgentAcceptPayment,
        metadata: InstructionMetadata,
        accounts: Vec<solana_instruction::AccountMeta>,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            amount: source.amount.into(),
            memo: source.memo.into(),
            start_time: source.start_time,
            end_time: source.end_time,
            accounts: sqlx::types::Json(accounts),
        }
    }
}

impl TryFrom<AgentAcceptPaymentRow>
    for crate::instructions::agent_accept_payment::AgentAcceptPayment
{
    type Error = carbon_core::error::Error;
    fn try_from(source: AgentAcceptPaymentRow) -> Result<Self, Self::Error> {
        Ok(Self {
            amount: *source.amount,
            memo: *source.memo,
            start_time: source.start_time,
            end_time: source.end_time,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::instructions::agent_accept_payment::AgentAcceptPayment
{
    fn table() -> &'static str {
        "agent_accept_payment_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "amount",
            "memo",
            "start_time",
            "end_time",
            "__accounts",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for AgentAcceptPaymentRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO agent_accept_payment_instruction (
                "amount",
                "memo",
                "start_time",
                "end_time",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9
            )"#,
        )
        .bind(&self.amount)
        .bind(&self.memo)
        .bind(self.start_time)
        .bind(self.end_time)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for AgentAcceptPaymentRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO agent_accept_payment_instruction (
                "amount",
                "memo",
                "start_time",
                "end_time",
                __signature, __instruction_index, __stack_height, __slot, __accounts
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "amount" = EXCLUDED."amount",
                "memo" = EXCLUDED."memo",
                "start_time" = EXCLUDED."start_time",
                "end_time" = EXCLUDED."end_time",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot,
                __accounts = EXCLUDED.__accounts
            "#,
        )
        .bind(&self.amount)
        .bind(&self.memo)
        .bind(self.start_time)
        .bind(self.end_time)
        .bind(&self.instruction_metadata.signature)
        .bind(self.instruction_metadata.instruction_index)
        .bind(self.instruction_metadata.stack_height)
        .bind(&self.instruction_metadata.slot)
        .bind(&self.accounts)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for AgentAcceptPaymentRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM agent_accept_payment_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for AgentAcceptPaymentRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM agent_accept_payment_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct AgentAcceptPaymentMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for AgentAcceptPaymentMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS agent_accept_payment_instruction (
                -- Instruction data
                "amount" NUMERIC(20) NOT NULL,
                "memo" NUMERIC(20) NOT NULL,
                "start_time" INT8 NOT NULL,
                "end_time" INT8 NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                __accounts JSONB NOT NULL,
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS agent_accept_payment_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
