//! This code was AUTOGENERATED using the Codama library.
pub mod agent_accept_payment_row;
pub mod agent_buyback_trigger_row;
pub mod agent_distribute_payments_row;
pub mod agent_initialize_row;
pub mod agent_transfer_extra_lamports_row;
pub mod agent_update_authority_row;
pub mod agent_update_buyback_bps_row;
pub mod agent_withdraw_row;
pub mod close_account_row;
pub mod cpi_event_row;
pub mod extend_account_row;
pub mod global_add_new_currency_row;
pub mod global_config_initialize_row;
pub mod global_remove_currency_row;
pub mod global_update_authorities_row;

pub use self::{
    agent_accept_payment_row::*, agent_buyback_trigger_row::*, agent_distribute_payments_row::*,
    agent_initialize_row::*, agent_transfer_extra_lamports_row::*, agent_update_authority_row::*,
    agent_update_buyback_bps_row::*, agent_withdraw_row::*, close_account_row::*, cpi_event_row::*,
    extend_account_row::*, global_add_new_currency_row::*, global_config_initialize_row::*,
    global_remove_currency_row::*, global_update_authorities_row::*,
};
use super::PumpAgentPaymentsInstruction;

pub struct PumpAgentPaymentsInstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for PumpAgentPaymentsInstructionsMigration {
    fn app(&self) -> &str {
        "pump-agent-payments"
    }

    fn name(&self) -> &str {
        "pump_agent_payments_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(AgentAcceptPaymentMigrationOperation),
            Box::new(AgentBuybackTriggerMigrationOperation),
            Box::new(AgentDistributePaymentsMigrationOperation),
            Box::new(AgentInitializeMigrationOperation),
            Box::new(AgentTransferExtraLamportsMigrationOperation),
            Box::new(AgentUpdateAuthorityMigrationOperation),
            Box::new(AgentUpdateBuybackBpsMigrationOperation),
            Box::new(AgentWithdrawMigrationOperation),
            Box::new(CloseAccountMigrationOperation),
            Box::new(ExtendAccountMigrationOperation),
            Box::new(GlobalAddNewCurrencyMigrationOperation),
            Box::new(GlobalConfigInitializeMigrationOperation),
            Box::new(GlobalRemoveCurrencyMigrationOperation),
            Box::new(GlobalUpdateAuthoritiesMigrationOperation),
            Box::new(CpiEventMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct PumpAgentPaymentsInstructionWithMetadata(
    pub PumpAgentPaymentsInstruction,
    pub carbon_core::instruction::InstructionMetadata,
    pub Vec<solana_instruction::AccountMeta>,
);

impl
    From<(
        PumpAgentPaymentsInstruction,
        carbon_core::instruction::InstructionMetadata,
        Vec<solana_instruction::AccountMeta>,
    )> for PumpAgentPaymentsInstructionWithMetadata
{
    fn from(
        value: (
            PumpAgentPaymentsInstruction,
            carbon_core::instruction::InstructionMetadata,
            Vec<solana_instruction::AccountMeta>,
        ),
    ) -> Self {
        PumpAgentPaymentsInstructionWithMetadata(value.0, value.1, value.2)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for PumpAgentPaymentsInstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let PumpAgentPaymentsInstructionWithMetadata(instruction, metadata, accounts) = self;
        match instruction {
            PumpAgentPaymentsInstruction::AgentAcceptPayment(instruction) => {
                let row = agent_accept_payment_row::AgentAcceptPaymentRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentBuybackTrigger(instruction) => {
                let row = agent_buyback_trigger_row::AgentBuybackTriggerRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentDistributePayments(instruction) => {
                let row = agent_distribute_payments_row::AgentDistributePaymentsRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentInitialize(instruction) => {
                let row = agent_initialize_row::AgentInitializeRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentTransferExtraLamports(instruction) => {
                let row =
                    agent_transfer_extra_lamports_row::AgentTransferExtraLamportsRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentUpdateAuthority(instruction) => {
                let row = agent_update_authority_row::AgentUpdateAuthorityRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentUpdateBuybackBps(instruction) => {
                let row = agent_update_buyback_bps_row::AgentUpdateBuybackBpsRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentWithdraw(instruction) => {
                let row = agent_withdraw_row::AgentWithdrawRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::CloseAccount(instruction) => {
                let row = close_account_row::CloseAccountRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::ExtendAccount(instruction) => {
                let row = extend_account_row::ExtendAccountRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::GlobalAddNewCurrency(instruction) => {
                let row = global_add_new_currency_row::GlobalAddNewCurrencyRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::GlobalConfigInitialize(instruction) => {
                let row = global_config_initialize_row::GlobalConfigInitializeRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::GlobalRemoveCurrency(instruction) => {
                let row = global_remove_currency_row::GlobalRemoveCurrencyRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::GlobalUpdateAuthorities(instruction) => {
                let row = global_update_authorities_row::GlobalUpdateAuthoritiesRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(
                    (**instruction).clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for PumpAgentPaymentsInstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let PumpAgentPaymentsInstructionWithMetadata(instruction, metadata, accounts) = self;
        match instruction {
            PumpAgentPaymentsInstruction::AgentAcceptPayment(instruction) => {
                let row = agent_accept_payment_row::AgentAcceptPaymentRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentBuybackTrigger(instruction) => {
                let row = agent_buyback_trigger_row::AgentBuybackTriggerRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentDistributePayments(instruction) => {
                let row = agent_distribute_payments_row::AgentDistributePaymentsRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentInitialize(instruction) => {
                let row = agent_initialize_row::AgentInitializeRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentTransferExtraLamports(instruction) => {
                let row =
                    agent_transfer_extra_lamports_row::AgentTransferExtraLamportsRow::from_parts(
                        instruction.clone(),
                        metadata.clone(),
                        accounts.clone(),
                    );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentUpdateAuthority(instruction) => {
                let row = agent_update_authority_row::AgentUpdateAuthorityRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentUpdateBuybackBps(instruction) => {
                let row = agent_update_buyback_bps_row::AgentUpdateBuybackBpsRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::AgentWithdraw(instruction) => {
                let row = agent_withdraw_row::AgentWithdrawRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::CloseAccount(instruction) => {
                let row = close_account_row::CloseAccountRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::ExtendAccount(instruction) => {
                let row = extend_account_row::ExtendAccountRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::GlobalAddNewCurrency(instruction) => {
                let row = global_add_new_currency_row::GlobalAddNewCurrencyRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::GlobalConfigInitialize(instruction) => {
                let row = global_config_initialize_row::GlobalConfigInitializeRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::GlobalRemoveCurrency(instruction) => {
                let row = global_remove_currency_row::GlobalRemoveCurrencyRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::GlobalUpdateAuthorities(instruction) => {
                let row = global_update_authorities_row::GlobalUpdateAuthoritiesRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            PumpAgentPaymentsInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(
                    (**instruction).clone(),
                    metadata.clone(),
                    accounts.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
