//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct GlobalConfig {
    pub bump: u8,
    pub protocol_authority: Pubkey,
    pub buyback_authority: Pubkey,
    pub supported_currencies_mint: [Pubkey; 10],
    pub tokenized_agent_sequence: u64,
}

impl GlobalConfig {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [149, 8, 156, 202, 160, 252, 176, 217] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
