//! This code was AUTOGENERATED using the Codama library.
use crate::{PumpAgentPaymentsDecoder, PROGRAM_ID};

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod bonding_curve;
pub mod global_config;
pub mod token_agent_payment_in_currency;
pub mod token_agent_payments;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PumpAgentPaymentsAccount {
    BondingCurve(Box<bonding_curve::BondingCurve>),
    GlobalConfig(Box<global_config::GlobalConfig>),
    TokenAgentPaymentInCurrency(Box<token_agent_payment_in_currency::TokenAgentPaymentInCurrency>),
    TokenAgentPayments(Box<token_agent_payments::TokenAgentPayments>),
}

impl<'a> carbon_core::account::AccountDecoder<'a> for PumpAgentPaymentsDecoder {
    type AccountType = PumpAgentPaymentsAccount;

    fn decode_account(
        &self,
        account: &'a solana_account::Account,
    ) -> Option<carbon_core::account::DecodedAccount<Self::AccountType>> {
        if account.owner != PROGRAM_ID {
            return None;
        }

        let data = account.data.as_slice();

        {
            if let Some(decoded) = bonding_curve::BondingCurve::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: PumpAgentPaymentsAccount::BondingCurve(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = global_config::GlobalConfig::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: PumpAgentPaymentsAccount::GlobalConfig(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) =
                token_agent_payment_in_currency::TokenAgentPaymentInCurrency::decode(data)
            {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: PumpAgentPaymentsAccount::TokenAgentPaymentInCurrency(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = token_agent_payments::TokenAgentPayments::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: PumpAgentPaymentsAccount::TokenAgentPayments(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }

        None
    }
}
