//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct TokenAgentPaymentInCurrency {
    pub mint: Pubkey,
    pub currency_mint: Pubkey,
    pub total_invoice_payments_made: u64,
    pub total_buyback: u64,
    pub total_withdrawals: u64,
    pub tokens_bought_back_and_burned: u64,
}

impl TokenAgentPaymentInCurrency {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != [225, 195, 81, 227, 115, 43, 25, 177] {
            return None;
        }

        let mut data_slice = data;

        data_slice = &data_slice[8..];

        borsh::BorshDeserialize::deserialize(&mut data_slice).ok()
    }
}
